[package]
authors = ["Juan Potato <hasantiny@gmail.com>"]
description = "Telegram Bot Api library"
keywords = ["telegram", "bot", "api"]
license = "MIT"
name = "tg_botapi"
readme = "README.md"
repository = "https://github.com/JuanPotato/rust-tg-botapi"
version = "0.4.1"

[dependencies]
derive_builder = "0.5.0"
hyper = "0.10.12"
hyper-native-tls = "0.2.4"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
debug_stub_derive = "0.3.0"


[dependencies.multipart]
default-features = false
features = ["client", "hyper"]
version = "0.13.1"
