[package]
authors = ["Juan Potato <hasantiny@gmail.com>"]
description = "Telegram Bot Api library"
keywords = ["telegram", "bot", "api"]
license = "MIT"
name = "tg_botapi"
readme = "README.md"
repository = "https://github.com/JuanPotato/rust-tg-botapi"
version = "0.1.2"

[dependencies]
derive_builder = "0.3.0"
enum_derive = "0.1.7"
hyper = "0.9.14"
multipart = "0.9.0"
serde = "0.9.6"
serde_derive = "0.9.6"
serde_json = "0.9.5"
