[package]
name = "tg_botapi"
version = "0.1.1"
authors = ["Juan Potato <hasantiny@gmail.com>"]

description = "Telegram Bot Api library"

repository = "https://github.com/JuanPotato/rust-tg-botapi"
readme = "README.md"

keywords = ["telegram", "bot", "api"]
build = "build.rs"
license = "MIT"

[build-dependencies]
serde_codegen = "0.8.21"

[dependencies]
serde = "0.8.23"
serde_json = "0.8.6"
hyper = "0.9.14"
multipart = "0.9.0"
