[package]
name = "tg_botapi"
version = "0.1.2"
authors = ["Juan Potato <hasantiny@gmail.com>"]

description = "Telegram Bot Api library"

repository = "https://github.com/JuanPotato/rust-tg-botapi"
readme = "README.md"

keywords = ["telegram", "bot", "api"]
license = "MIT"

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
hyper = "0.9.14"
multipart = "0.9.0"
